language: bash

before_install:
    - cd ch0x04
    - cd code
    - ls
    - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"   
    - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/worldcupplayerinfo.tsv"
    - sudo apt-get update && sudo apt-get install imagemagick
    - sudo apt-get install ghostscript
    - sudo sudo apt-get install p7zip-full
    - 7z x  web_log.tsv.7z 
    - ls
script:  
    - bash dataProcess.sh  -r -p -n -a     
    - bash task3.sh  -o -p -m -c -f -u "/pub/winvn/readme.txt"
    - mkdir ImgOutPut 
    - ls
    - bash  imageP.sh  ../data -q 50 -r 50 -w "hello" -p "pre" -s "suf" -c
    - ls ImgOutPut
    - cat log.txt
